### ISSUE TITLE
Resource exhausted (Resource temporarily unavailable) error

### ISSUE THREAD

**Issue by devilus** [input-output-hk/cardano-graphql#435] opened 2021-02-24 18:18 UTC
```
{ os:
   { arch: 'x64',
     cpus:
      { count: 4, model: 'Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz' },
     release: '4.18.0-240.10.1.el8_3.x86_64',
     totalMem: 8145096704,
     type: 'Linux' },
  version: '3.2.0' 
}
```
#### Platform

CentOS 8 / Ubuntu 20.04

**Platform version**: 

#### Runtime

Docker

**Runtime version**: 
```
node -v -> v10.23.1

docker version -> 
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:08 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Steps to reproduce the bug

`curl -X POST -H "Content-Type: application/json" -d '{"query": "{ cardanoDbMeta { initialized syncPercentage }}"}' http://localhost:3100/graphql`

`{"errors":[{"message":"Error: \ncardano-cli: Network.Socket.connect: <socket: 11>: resource exhausted (Resource temporarily unavailable)","locations":[{"line":1,"column":3}],"path":["cardanoDbMeta"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Error: ","cardano-cli: Network.Socket.connect: <socket: 11>: resource exhausted (Resource temporarily unavailable)"," at Object.<anonymous> (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:143:35)"," at Generator.throw (<anonymous>)"," at rejected (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:6:65)"," at runMicrotasks (<anonymous>)"," at processTicksAndRejections (internal/process/task_queues.js:93:5)"]}}}],"data":null}`

After 2-5 attempts:
`{"data":{"cardanoDbMeta":{"initialized":true,"syncPercentage":100}}}`

And then again the same error.

**Comment by CyberCyclone** [comment] 2021-02-25 21:25
Sounds like a similar issue to what I am having:

<img width="1647" alt="Screen Shot 2021-02-26 at 7 23 03 am" src="https://user-images.githubusercontent.com/4373888/109219717-b01f2c00-7803-11eb-821d-2d36d2fd2225.png">

**Comment by rhyslbw** [comment] 2021-02-25 22:18
Thanks for the report @devilus and @CyberCyclone. I'll see if I can reproduce

**Comment by CyberCyclone** [comment] 2021-02-28 03:42
@rhyslbw If it helps replicating the issue, it happens a lot when syncing from scratch. The screenshot I added above I haven't seen happen again, but the cardano-cli error happens a lot when doing a fresh sync. No errors are thrown in the console and everything seems to be running fine (it still continues to sync the blockchain and populate Postgres).

When running the command from a completely synced node, if you leave it for a while it might throw the error, but after that the command returns correctly (running the command repetitively for 30 seconds with no issues). Then if you leave it for a while it might throw the error again.

**Comment by xdzurman** [comment] 2021-03-01 08:56
I can confirm this occurs very often also when sending transactions - e.g. sending a transaction every 10 seconds, 12 pass, 5 fail. The node is fully synced

**Comment by islishude** [comment] 2021-03-02 05:23
I can also confirm this

**Comment by rhyslbw** [comment] 2021-03-03 06:45
I'm still trying to come up with a reproduction. What are your system specs @xdzurman and @islishude ?

**Comment by islishude** [comment] 2021-03-03 06:50
I have upgraded aws ec2 from c5.xlarge to c5.2xlarge and no such error now

**Comment by CyberCyclone** [comment] 2021-03-03 06:50
> I'm still trying to come up with a reproduction. What are your system specs @xdzurman and @islishude ?

Would it help if I spun up a server temporarily and gave you access?

The specs for mine that had the issues was an 8 core 16GB RAM Digital Ocean droplet. Occasionally a fully synced node has the issue, but syncing from scratch I've had issues with 2 servers.

**Comment by rhyslbw** [comment] 2021-03-03 07:08
Thanks for the offer @CyberCyclone, but @islishude's response is enough to proceed. I have a couple of things to look at, but will probably have to make one of the more resource intensive operations optional.

**Comment by islishude** [comment] 2021-03-03 08:54
update.

I met again, but only once or twice in an hour

**Comment by rhyslbw** [comment] 2021-03-04 12:58
I'm aiming to have a fix in `master` within 24hrs. A new release is due out early next week

**Comment by rhyslbw** [comment] 2021-03-05 07:36
I'll be setting up a load test prior to merging this to `master` to try and reproduce the transaction sending failure, although I suspect this was a side-effect of the ledger-state query running. Might not get this merged until next week now, but feel free to try the linked PR branch instread.

**Closed** 2021-03-18 12:09 UTC
Labels: BUG, PRIORITY:MEDIUM, SEVERITY:MEDIUM

**Comment by CherryDT** [comment] 2021-05-02 18:40
This still happens to me when I send several requests in a row to GraphQL. What resources are getting exhausted here? ulimit should be sufficient, anything I can change?

**Comment by dmitri-safine** [comment] 2021-05-10 04:45
I also see this error while syncing. AWS EC2  `m5.2xlarge` instance

**Comment by islishude** [comment] 2021-05-10 04:47
try https://github.com/input-output-hk/cardano-node/releases/tag/1.26.2

**Comment by dmitri-safine** [comment] 2021-05-10 06:53
Still seeing same errors as above with 1.26.2 during sync and also `syncPercentage` field stopped working. 
```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field CardanoDbMeta.syncPercentage.",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "cardanoDbMeta",
        "syncPercentage"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field CardanoDbMeta.syncPercentage.",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:560:13)",
            "    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:495:19)",
            "    at resolveField (/app/node_modules/graphql/execution/execute.js:435:10)",
            "    at executeFields (/app/node_modules/graphql/execution/execute.js:275:18)",
            "    at collectAndExecuteSubfields (/app/node_modules/graphql/execution/execute.js:713:10)",
            "    at completeObjectValue (/app/node_modules/graphql/execution/execute.js:703:10)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:591:12)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:557:21)",
            "    at /app/node_modules/graphql/execution/execute.js:492:16",
            "    at runMicrotasks (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by CherryDT** [comment] 2021-05-10 08:25
I have this also when sync is done by the way. Especially if I _didn't_ send any request for a while, the first request then usually hits this error.

**Comment by islishude** [comment] 2021-05-10 08:35
you should restart graphql services after upgrading node

**Comment by rhyslbw** [comment] 2021-05-11 05:55
@CherryDT Are the other services all running as expected? This can happen if `cardano-db-sync` gets into a crash loop, so it's best to rule that out first

**Comment by CherryDT** [comment] 2021-05-11 06:13
I don't see anything in the docker-compose logs indicating otherwise. The only "errors" are the occasional
```
cardano-node_1              | [459a0354:cardano.node.DnsSubscription:Error:659233] [2021-05-11 01:49:05.34 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 52.28.21.120:3001 ExceededTimeLimit (ChainSync (Header (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) ('[] *))))))) (Tip HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) ('[] *))))))) (ServerAgency TokNext TokMustReply)] *))))))) (Tip HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) ('[] *))))))) (ServerAgency TokNext TokMustReply))) 20snnet.iohk.io" Connection Attempt End, destination 52.29.138.13:3001 outcome: ConnectSuccessLast
```
and
```
cardano-node_1              | [459a0354:cardano.node.DnsSubscription:Error:658706] [2021-05-11 01:10:54.40 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 52.29.138.13:3001 MuxError MuxBearerClosed "<socket: 27> closed when reading data, waiting on next header True"           | [459a0354:cardano.node.ErrorPolicy:Warning:53] [2021-05-11 01:10:54.40 UTC] IP 52.29.138.13:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError MuxBearerClosed "<socket: 27> closed when reading data, waiting on next header True"))) 20s 20s              | [459a0354:cardano.node.DnsSubscription:Notice:659175] [2021-05-11 01:10:55.42 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt Start, destination 3.133.45.145:3001
cardano-node_1              | [459a0354:cardano.node.DnsSubscription:Notice:659176] [2021-05-11 01:10:55.45 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt Start, destination 18.158.196.38:3001
cardano-node_1              | [459a0354:cardano.node.DnsSubscription:Notice:659176] [2021-05-11 01:10:55.46 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt End, destination 18.158.196.38:3001 outcome: ConnectSuccessLast
cardano-node_1              | [459a0354:cardano.node.ErrorPolicy:Notice:53] [2021-05-11 01:10:55.46 UTC] IP 3.133.45.145:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1
```

**Comment by CherryDT** [comment] 2021-05-18 15:35
It's happening again - trying to get syncPercentage shows this problem, while getting protocolParams for example works. Already upgraded cardano-node, restarted everything several times, etc. - After a while this always happens. What can I do?

**Comment by rhyslbw** [comment] 2021-07-02 10:26
Sorry @CherryDT , I missed your responses. If you're still stuck, you can try the `master` branch which is very close to a release candidate for version 5.
