### ISSUE TITLE
Queries sometimes throwing cannot read property 'schema' of undefined

### ISSUE THREAD

**Issue by fash** [input-output-hk/cardano-graphql#484] opened 2021-04-27 09:44 UTC
![cardano-working](https://user-images.githubusercontent.com/699161/116221568-a6536f80-a745-11eb-845e-e9ea40c0d127.png)
![cardano-broken](https://user-images.githubusercontent.com/699161/116221598-ac495080-a745-11eb-802a-c15febef9d57.png)

#### Platform

- [x] Linux / Ubuntu

**Platform version**: 

#### Runtime
- [x] Docker

### Steps to reproduce the bug
1. Run graphql and let it sync
2. Open playground or command line
3. Run the attached query 
4. Result is inconsistent i.e. most times it throws and error and other times it returns the desired result
[cardano-query.txt](https://github.com/input-output-hk/cardano-graphql/files/6383540/cardano-query.txt)

### What is the expected behavior?
Return the same result each time it is queries

**Comment by rhyslbw** [comment] 2021-04-29 14:28
The error you're reporting could be due to `cardano-db-sync` is crashing and restarting. Can you provide a sample of the docker-compose stack logs?

**Comment by fash** [comment] 2021-04-29 18:23
[CoinFirm.txt](https://github.com/input-output-hk/cardano-graphql/files/6400797/CoinFirm.txt)

Recent logs. Let mw know your thoughts. Thanks

**Comment by rhyslbw** [comment] 2021-04-30 06:25
Ok this is actually a duplicate of #464 . See https://github.com/input-output-hk/cardano-graphql/issues/464#issuecomment-812301489 as the solution to workaround this until the next release

**Closed by rhyslbw** 2021-04-30 06:25 UTC
