### ISSUE TITLE
Improvement: Field Aliasing

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#650] opened 2022-01-12 00:51 UTC
Field aliasing isn't resolving correctly. Aliasing is often used, such as the below query. The stake pool `id` field often clashes with other frameworks, so aliasing it on the fly is more manageable than mapping afterwards.

```
query stakePools {
  stakePools(limit: 10) {
    poolId: id
  }
}
```

The above query works correctly using Hasura while cardano-graphql throws the below:

```
{
      "message": "Cannot return null for non-nullable field StakePool.id.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "stakePools",
        0,
        "poolId"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field StakePool.id.",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:560:13)",
            "    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:495:19)",
            "    at resolveField (/app/node_modules/graphql/execution/execute.js:435:10)",
            "    at executeFields (/app/node_modules/graphql/execution/execute.js:275:18)",
            "    at collectAndExecuteSubfields (/app/node_modules/graphql/execution/execute.js:713:10)",
            "    at completeObjectValue (/app/node_modules/graphql/execution/execute.js:703:10)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:591:12)",
            "    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:495:19)",
            "    at /app/node_modules/graphql/execution/execute.js:618:25",
            "    at Array.forEach (<anonymous>)"
          ]
        }
      }
    },
```

**Comment by rhyslbw** [comment] 2022-01-12 10:53
Duplicate of #164

**Closed by rhyslbw** 2022-01-12 10:53 UTC
