### ISSUE TITLE
Does Cardano GraphQL 5.0.0 support Alonzo?

### ISSUE THREAD

**Issue by vae520283995** [input-output-hk/cardano-graphql#549] opened 2021-07-26 16:14 UTC
@rhyslbw  Hi, I am an exchange developer, if GraphQL 5.0.0 supports Alonzo, I will prepare to upgrade from 4.0.0 to 5.0.0

**Comment by rhyslbw** [comment] 2021-07-27 05:18
Dupe of #539

**Closed by rhyslbw** 2021-07-27 05:18 UTC
