### ISSUE TITLE
New version 3.2.0 Continuously querying the ledger state 

### ISSUE THREAD

**Issue by asnakep** [input-output-hk/cardano-graphql#417] opened 2021-02-02 16:41 UTC
Hello Team,

with this new version which require node socket and cardano-cli (may be for mutation submit signed tx feature)
I noticed that at every launch and then every some minutes while running, a specific query on is launched against ledger state.

Just would like to know if this is the normal behaviour.

Is a costly operation an make unusable my machine during every query execution time.
I can't neither run it on my 8gb server where I run two cardano-nodes and db-sync, the query get killed to prevent nodes
restart.

For now I rollbacked to 3.1.1 and adapted the migration sql file for db-sync 8.0.0 (column merkel to merkle of block table).

Thanks
kind regards,
Emanuele

**Comment by rhyslbw** [comment] 2021-02-04 04:13
Yes this is intended behaviour, as the ledger state contains data used to calculate ada supply, however will also be used to present more information with future features. It's dumped every 10 minutes. Your system is not meeting the minimum requirements for running two instances of `cardano-node` plus `cardano-db-sync`, so consider moving to a slightly higher rated machine or separating your block producer, which is the suggested security model anyway.

**Closed by rhyslbw** 2021-02-04 04:13 UTC

**Comment by asnakep** [comment] 2021-02-04 07:25
I never said I run block producer and relay together.
What I said is:
on my server, 8gb mem, I  run two relays and db-sync.
And query ledger state get killed to prevent relays restart.

Thanks for the explanation.

**Comment by asnakep** [comment] 2021-02-04 07:30
so before to tell me that my system doesn't meet security requirements, be sure you fully understand what I wrote
thank you!

**Comment by rhyslbw** [comment] 2021-03-05 07:48
> I never said I run block producer and relay together.

Agree, apologies for the invalid assumption.

https://github.com/input-output-hk/cardano-graphql/pull/441 removes the use of the `ledger-state` query, so once it's released you can freely update to a newer version.
